### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by lexur22** [oleksandrblazhko/ai204-dorozhkin#11]

**Comment by lexur22** [comment]
1) FR2.3 Користувач може створити набір власних вправ.
Змінюємо на:
Користувач може створити набір власних вправ, додати чи видалити вправи.

FR1.5 Споживач повинен надати дані банківської картки.
Змінюємо на:
Споживач може надати дані банківської картки.

FR1.1 Система повинна надати весь асортимент продуктів
Змінюємо на:
Система повинна надати весь асортимент продуктів, та у першу чергу магазини які можуть бути проспонсовані власником.

**Comment by lexur22** [comment]
2) 
Розподілена система - значення дорівнює 4, обрано через навантаженність продукту, так як обробка даних проходить на двух оремих серверах.
Спеціальні вимоги до навчання користувачів - - значення дорівнює 2, обрано через те що наявні додаткові потреби у вигляді заповнення банківських данних, в цілому інтерфейс для нового користувача простий та зрозумілий.

**Comment by oleksandrblazhko** [comment]
Коментарі до рішення 1-го завдання:
1) умова "атомарність" порушується, якщо описано декілька дій зразу
2) умова "завершеність" порушується, якщо немає формату Subject-Action-Object
3) "безкоштовніть реалізації" порушується, якщо, наприклад, 
використовуються графічний інтерфейс
У вас не всі завдання виконано правильно.

Оцінка = 2 бали
