### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by lexur22** [oleksandrblazhko/ai204-dorozhkin#3]

**Comment by lexur22** [comment]
1) Інформаційна потреба - фізичний стан здоров'я.
Я не вказував нічого у комірках, бо:
Доступність: інформація про підтримку власного фіз. стану здоров'я є надмірною в мережі "Інтернет".
Зрозумілість: ми розуміємо основні фактори забезпечення гарного фіз. стану завдяки знанням, які мали надаватися під час шкільних занятть з біології та основ здоров'я. Більш поглиблену інформацію можна без проблем знайти в мережі "Інтернет".
Цінність: інформація про фіз. стан здоров'я є основним чинником здорового життя, тобто знання про здоров'я є неоцінимою цінністю.
Актуальність: так як кожна людина хоче бути здоровою, щоб у неї нічого не боліло, та не було зайвих проблем, людина завжди буде потребувати інформацію про підтримку фіз. стану, тобто ця тематика буде завжди актуальною.

**Comment by lexur22** [comment]
2. Мета мого програмного продукту: надати можливість повноцінно проявити любов до створення скульптур, потрібен гарний стан фізичного здоров’я, підтриматиякий може їжа.
1) Переглядати фото нових робіт, ставити "Подобається", загружати свої фото.
Цей прецендент надає можливість проявляти любов до створення скульптур, а також отримувати її у наслідок викладання своїх робіт.
2) Замовляти та оплачувати їжу.
Цей прецендент надає можливість обирати корисну їжу, яка повинна підтримувати фіз. стан здоров'я користувача.
3) Займатися спортом вдома.
Цей прецендент надає можливість отримати та вдосконалити свій фіз. стан у наслідок виконання фізичних вправ.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
